apiVersion: v1
kind: Service
metadata:
  name: tms-api
spec:
  type: NodePort
  selector:
    app: tms-api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

#minikube service tms-api

#Save this as a ~/.kube/config file inside the action runner
#Use it to authenticate to your local Minikube cluster (assuming the runner can reach it 
#— which only works if you’re self-hosting the runner or tunneling)